#! /usr/bin/env bash
CHIPLAB_HOME=$(realpath "$(dirname "$0")")
CHIPLAB_TOOLCHAINS=$CHIPLAB_HOME/toolchains
CHIPLAB_LA32RCOMPILER=$CHIPLAB_TOOLCHAINS/loongson-gnu-toolchain-8.3-x86_64-loongarch32r-linux-gnusf-v2.0/bin
CHIPLAB_LA32RQEMU=$CHIPLAB_TOOLCHAINS/la32r-QEMU-x86_64-ubuntu-22.04
CHIPLAB_LA32RNEMU=$CHIPLAB_TOOLCHAINS/la32r-nemu
export CHIPLAB_HOME
export NEMU_HOME=$CHIPLAB_LA32RNEMU
export PATH=$CHIPLAB_LA32RCOMPILER:$PATH
export PATH=$CHIPLAB_LA32RQEMU:$PATH
